NEWSAPI_KEY = ""
REDDIT_CLIENT_ID = ""
REDDIT_CLIENT_SECRET = ""
REDDIT_USER_AGENT = "python:data-dashboard:v1.0 (by /u/[enter username here])"
AVIATIONSTACK_KEY = ""
GOVERNMENT_DATA_KEY = ""

DEBUG = True
LOG_LEVEL = "INFO"

THEME = "green"
APPEARANCE_MODE = "System"
WINDOW_SIZE = "1200x800"

DEFAULT_LIMIT = 10
DEFAULT_COUNTRY = "us"
DEFAULT_LANGUAGE = "en"

CACHE_ENABLED = True
CACHE_DURATION = 300
